In [1]:
import numpy as np

In [2]:
a=np.array([5,1,3,6,4])
np.sort(a)
a

array([5, 1, 3, 6, 4])

In [4]:
a.sort()
a

array([1, 3, 4, 5, 6])

In [11]:
b=np.random.randint(1,100,24).reshape(6,4)
print(b)
np.sort(b,axis=0)

[[16 70 36  4]
 [28  6 35 16]
 [12 43 88 77]
 [75 40 85 57]
 [46 94 44  3]
 [ 8 87 59 78]]


array([[ 8,  6, 35,  3],
       [12, 40, 36,  4],
       [16, 43, 44, 16],
       [28, 70, 59, 57],
       [46, 87, 85, 77],
       [75, 94, 88, 78]])

In [14]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distributi

In [25]:
a=np.array([1,2,3,4,5,6])
new=np.array_split(a,4)
print(new)
new[0]

[array([1, 2]), array([3, 4]), array([5]), array([6])]


array([1, 2])

In [30]:
arr=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
new=np.array_split(arr,3,axis=0)
print(new)
new[0]

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


array([[1, 2],
       [3, 4]])

In [34]:
a=np.array([[1,2,3],[4,5]])
for i in a:
    print(i)

[1, 2, 3]
[4, 5]


<ipython-input-34-6fb615b60b82>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  a=np.array([[1,2,3],[4,5]])


In [ ]:
for i in a:
    print(i)